208 display frame type and motor directions on motor test page
Avis-Drone-Labs/FGCS pull request #276
Opened 2024-06-11 18:36 UTC by ShadabMir

Needs testing with a flight controller.

2024-06-13 20:29 UTC, 1Blademaster commented on gcs/src/components/config/motorTest.jsx
> +export default function Motortestpanel() {
Change the name of this component to `MotorTestPanel`, components should be PascalCase

2024-06-13 20:29 UTC, 1Blademaster commented on gcs/src/components/config/motorTest.jsx
> +    } else {
You can make this `if (connected) { ...` instead of having the if and else

2024-06-13 20:29 UTC, 1Blademaster commented on gcs/src/components/config/motorTest.jsx
> +      let currentFrameClass = data.frame_class
If these don't change, then just make them with `const` instead of `let`

2024-06-13 20:29 UTC, 1Blademaster commented on gcs/src/components/config/motorTest.jsx
> +          setFrameTypeDirection(
Here maybe create a new variable which stores the frame information, e.g. `const frameInfo = FRAME_CLASS_MAP[currentFrameClass].frametype[currentFrameType]`. Then you can easily access this below.

2024-06-13 20:29 UTC, 1Blademaster commented on gcs/src/components/config/motorTest.jsx
> +          {frameClass != null && (
Change this to `!==`

2024-06-13 20:29 UTC, 1Blademaster commented on gcs/src/components/config/motorTest.jsx
> +          {frameTypename != null && (
Change this to `!==`

2024-06-13 20:29 UTC, 1Blademaster commented on gcs/src/components/config/motorTest.jsx
> +          {frameTypeOrder != null && (
Change this to `!==`

2024-06-13 20:29 UTC, 1Blademaster commented on gcs/src/helpers/mavlinkConstants.js
> +export const LETTERS = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']
If the frame types have frames with 12 motors, then shouldn't the `LETTERS` array include 12 letters? Also can you rename this to something more clear, e.g. `MOTOR_LETTER_LABELS`?

2024-07-24 15:37 UTC, NexInfinite requested changes
Very minor changes but two functions are missing return types

2024-07-24 15:37 UTC, NexInfinite commented on radio/app/controllers/frameController.py
> +    def __init__(self, drone: Drone):
should have return type of None on init
```py
def __init__(self, drone: Drone) -> None:
    ...
```

2024-07-24 15:37 UTC, NexInfinite commented on radio/tests/__init__.py
>  def falcon_test(
needs return type

2024-07-24 15:37 UTC, NexInfinite commented on radio/tests/__init__.py
>  def falcon_test(
I have just realised this was _my_ code and I remember why it has no return type so ignore this

2024-07-24 20:42 UTC, merged