Created functionality for ignoring the update notification until a new update comes out, then it shows it again.
Avis-Drone-Labs/FGCS pull request #413
Opened 2024-11-28 21:30 UTC by harry-bond

Ignore the mistake in vv1.1.5 that's because i had to manually set it to show it coming up and i just misspelt it. But this is how it looks. Can have a go at changing the styling if you'd prefer something else or even changing the writing to like "Never" or something?

![Screenshot 2024-11-28 202006](https://github.com/user-attachments/assets/eaa2e033-98cd-4ac1-8719-3643ab32728f)

2024-11-28 21:38 UTC, NexInfinite commented
Maybe make the buttons be side by side, and have the "do not show again" on the left hand side. Also the x in the top right corner has a default outline, can you disable it? The new tailwind v4 (soon to be released) will fix this but its better to do so now anyway.

2024-11-28 22:31 UTC, harry-bond commented
Honestly, I have no idea how to style just that x in the corner because it is kind of built in to react Modal as OnClose, I'm also not sure why when pressing tab it just skips the new button I've added not letting it focus on it?

2024-12-04 17:58 UTC, NexInfinite commented
We can go over it another time, its not that deep. You'd need to look into the styling in mantine which is a whole can of worms.

2024-12-04 18:01 UTC, NexInfinite requested changes
Codes looking good! Here's some things that would keep it a bit more consistent with our code styles.

2024-12-04 18:01 UTC, NexInfinite commented on gcs/src/components/SingleRunWrapper.jsx
> +  //Checks there is an update that the user has not already dismissed
Can you add a space between `//` and the comment? For example: `// Here's my comment`

2024-12-04 18:01 UTC, NexInfinite commented on gcs/src/components/SingleRunWrapper.jsx
> +            target='_blank'
We won't need `target='_blank'` as its not opening a web page

2024-12-04 18:01 UTC, NexInfinite commented on gcs/src/components/SingleRunWrapper.jsx
> +            className=''
if theres nothing in `className` then we can get rid of it. Same with line 131.

2024-12-04 18:25 UTC, david-gasinski commented
@NexInfinite  Potentially add a "maybe later" option? I find myself often needing to use some software but not wanting to update it straight away. "Maybe later" will just close the dialog and open it again next time the app is ran.

2024-12-04 18:28 UTC, NexInfinite commented
Clicking x would be the maybe later but that could be a nice touch, @harry-bond feel free to mess around with that idea

2024-12-05 18:10 UTC, NexInfinite commented
We think its better to change the "do not show again" to be "skip update" and then add some text showing the user how to manually update in the top right of the screen. Reach out if you want some better wording.

2025-01-05 03:54 UTC, 1Blademaster requested changes

2025-01-05 03:54 UTC, 1Blademaster commented on gcs/src/components/SingleRunWrapper.jsx
> +              Do not show again
Can you change the wording to "Skip update" please

2025-01-05 16:53 UTC, NexInfinite approved these changes
LGTM

2025-01-05 17:28 UTC, 1Blademaster approved these changes

2025-01-05 18:13 UTC, merged